[package]
name = "unkobot"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
nostr-sdk = "0.37.0"
tokio = { version = "1.42.0", features = ["full"] }
tracing-subscriber = "0.3.19"
