name: event_sender

on: workflow_dispatch

#on:
#  schedule:
#    - cron: '0 9 * * *'

jobs:
  sender:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build unkobot
        run: nix build .#unkobot
      - name: Run unkobot
        run: ./result/bin/unkobot "${{ secrets.UNKOBOT_SECRET_KEY }}" "$(cat pubkey.txt)"
